image: maven:latest

stages:
  - compile
  - test
  - install

compile:
  stage: compile
  script:
      - mvn compile
      - mvn clean

test:
  stage: test
  script:
      - mvn test
      - mvn clean

install:
  stage: install
  script:
      - mvn install
      - mvn clean