server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:db}
    username: ${MYSQL_USER:springuser}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      maxFileSize: 51200KB
      maxRequestSize: 51200KB

  security:
    user:
      name: admin
      password: SuperSecretAdmin



springdoc:
  swagger-ui:
    path: /swagger/index.html
  api-docs:
    path: /swagger/api-docs
